language: python
python:
    - "2.7"
install:
    - pip install pep8 --use-mirrors
    - pip install requests tornado bs4
before_script:
    - "pep8 --exclude=migrations --ignore=E501,E225 src"
script:
    - python setup.py test
